
version: '3.8'

services:
  ft-deployment-tool:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
      - ~/.ssh:/root/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_ENV=production
      - ANSIBLE_HOST_KEY_CHECKING=False
    restart: unless-stopped
